// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.ipolyzos.models;

public interface ClickEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.ipolyzos.models.ClickEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventTime = 1;</code>
   * @return The eventTime.
   */
  java.lang.String getEventTime();
  /**
   * <code>string eventTime = 1;</code>
   * @return The bytes for eventTime.
   */
  com.google.protobuf.ByteString
      getEventTimeBytes();

  /**
   * <code>string eventType = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <code>string eventType = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string productId = 3;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 3;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string categoryId = 4;</code>
   * @return The categoryId.
   */
  java.lang.String getCategoryId();
  /**
   * <code>string categoryId = 4;</code>
   * @return The bytes for categoryId.
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string categoryCode = 5;</code>
   * @return The categoryCode.
   */
  java.lang.String getCategoryCode();
  /**
   * <code>string categoryCode = 5;</code>
   * @return The bytes for categoryCode.
   */
  com.google.protobuf.ByteString
      getCategoryCodeBytes();

  /**
   * <code>string brand = 6;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 6;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string price = 7;</code>
   * @return The price.
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 7;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>string userId = 8;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 8;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string userSession = 9;</code>
   * @return The userSession.
   */
  java.lang.String getUserSession();
  /**
   * <code>string userSession = 9;</code>
   * @return The bytes for userSession.
   */
  com.google.protobuf.ByteString
      getUserSessionBytes();
}
