// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.ipolyzos.models;

public final class EventOuter {
  private EventOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_ipolyzos_models_ClickEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_ipolyzos_models_ClickEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\022io.ipolyzos.models\"\262\001\n\nCl" +
      "ickEvent\022\021\n\teventTime\030\001 \001(\t\022\021\n\teventType" +
      "\030\002 \001(\t\022\021\n\tproductId\030\003 \001(\t\022\022\n\ncategoryId\030" +
      "\004 \001(\t\022\024\n\014categoryCode\030\005 \001(\t\022\r\n\005brand\030\006 \001" +
      "(\t\022\r\n\005price\030\007 \001(\t\022\016\n\006userId\030\010 \001(\t\022\023\n\013use" +
      "rSession\030\t \001(\tB\016B\nEventOuterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_ipolyzos_models_ClickEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_ipolyzos_models_ClickEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_ipolyzos_models_ClickEvent_descriptor,
        new java.lang.String[] { "EventTime", "EventType", "ProductId", "CategoryId", "CategoryCode", "Brand", "Price", "UserId", "UserSession", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
