// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/event.proto

package io.ipolyzos.models;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.ipolyzos.models.JEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string eventTime = 1;</code>
     * @return The eventTime.
     */
    java.lang.String getEventTime();
    /**
     * <code>string eventTime = 1;</code>
     * @return The bytes for eventTime.
     */
    com.google.protobuf.ByteString
        getEventTimeBytes();

    /**
     * <code>string eventType = 2;</code>
     * @return The eventType.
     */
    java.lang.String getEventType();
    /**
     * <code>string eventType = 2;</code>
     * @return The bytes for eventType.
     */
    com.google.protobuf.ByteString
        getEventTypeBytes();

    /**
     * <code>string productId = 3;</code>
     * @return The productId.
     */
    java.lang.String getProductId();
    /**
     * <code>string productId = 3;</code>
     * @return The bytes for productId.
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>string categoryId = 4;</code>
     * @return The categoryId.
     */
    java.lang.String getCategoryId();
    /**
     * <code>string categoryId = 4;</code>
     * @return The bytes for categoryId.
     */
    com.google.protobuf.ByteString
        getCategoryIdBytes();

    /**
     * <code>string categoryCode = 5;</code>
     * @return The categoryCode.
     */
    java.lang.String getCategoryCode();
    /**
     * <code>string categoryCode = 5;</code>
     * @return The bytes for categoryCode.
     */
    com.google.protobuf.ByteString
        getCategoryCodeBytes();

    /**
     * <code>string brand = 6;</code>
     * @return The brand.
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 6;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string price = 7;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 7;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>string userId = 8;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 8;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string userSession = 9;</code>
     * @return The userSession.
     */
    java.lang.String getUserSession();
    /**
     * <code>string userSession = 9;</code>
     * @return The bytes for userSession.
     */
    com.google.protobuf.ByteString
        getUserSessionBytes();
  }
  /**
   * Protobuf type {@code io.ipolyzos.models.JEvent}
   */
  public static final class JEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.ipolyzos.models.JEvent)
      JEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JEvent.newBuilder() to construct.
    private JEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JEvent() {
      eventTime_ = "";
      eventType_ = "";
      productId_ = "";
      categoryId_ = "";
      categoryCode_ = "";
      brand_ = "";
      price_ = "";
      userId_ = "";
      userSession_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              eventTime_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              eventType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              productId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              categoryId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              categoryCode_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              price_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              userSession_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ipolyzos.models.Event.internal_static_io_ipolyzos_models_JEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ipolyzos.models.Event.internal_static_io_ipolyzos_models_JEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ipolyzos.models.Event.JEvent.class, io.ipolyzos.models.Event.JEvent.Builder.class);
    }

    public static final int EVENTTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object eventTime_;
    /**
     * <code>string eventTime = 1;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public java.lang.String getEventTime() {
      java.lang.Object ref = eventTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventTime_ = s;
        return s;
      }
    }
    /**
     * <code>string eventTime = 1;</code>
     * @return The bytes for eventTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTimeBytes() {
      java.lang.Object ref = eventTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object eventType_;
    /**
     * <code>string eventType = 2;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <code>string eventType = 2;</code>
     * @return The bytes for eventType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object productId_;
    /**
     * <code>string productId = 3;</code>
     * @return The productId.
     */
    @java.lang.Override
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string productId = 3;</code>
     * @return The bytes for productId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORYID_FIELD_NUMBER = 4;
    private volatile java.lang.Object categoryId_;
    /**
     * <code>string categoryId = 4;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public java.lang.String getCategoryId() {
      java.lang.Object ref = categoryId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryId_ = s;
        return s;
      }
    }
    /**
     * <code>string categoryId = 4;</code>
     * @return The bytes for categoryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryIdBytes() {
      java.lang.Object ref = categoryId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORYCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object categoryCode_;
    /**
     * <code>string categoryCode = 5;</code>
     * @return The categoryCode.
     */
    @java.lang.Override
    public java.lang.String getCategoryCode() {
      java.lang.Object ref = categoryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string categoryCode = 5;</code>
     * @return The bytes for categoryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryCodeBytes() {
      java.lang.Object ref = categoryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 6;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 6;</code>
     * @return The brand.
     */
    @java.lang.Override
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 6;</code>
     * @return The bytes for brand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 7;
    private volatile java.lang.Object price_;
    /**
     * <code>string price = 7;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 7;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 8;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 8;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 8;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERSESSION_FIELD_NUMBER = 9;
    private volatile java.lang.Object userSession_;
    /**
     * <code>string userSession = 9;</code>
     * @return The userSession.
     */
    @java.lang.Override
    public java.lang.String getUserSession() {
      java.lang.Object ref = userSession_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userSession_ = s;
        return s;
      }
    }
    /**
     * <code>string userSession = 9;</code>
     * @return The bytes for userSession.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserSessionBytes() {
      java.lang.Object ref = userSession_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEventTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventTime_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventType_);
      }
      if (!getProductIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productId_);
      }
      if (!getCategoryIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, categoryId_);
      }
      if (!getCategoryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, categoryCode_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, brand_);
      }
      if (!getPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, price_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userId_);
      }
      if (!getUserSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userSession_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEventTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventTime_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventType_);
      }
      if (!getProductIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productId_);
      }
      if (!getCategoryIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, categoryId_);
      }
      if (!getCategoryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, categoryCode_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, brand_);
      }
      if (!getPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, price_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userId_);
      }
      if (!getUserSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userSession_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.ipolyzos.models.Event.JEvent)) {
        return super.equals(obj);
      }
      io.ipolyzos.models.Event.JEvent other = (io.ipolyzos.models.Event.JEvent) obj;

      if (!getEventTime()
          .equals(other.getEventTime())) return false;
      if (!getEventType()
          .equals(other.getEventType())) return false;
      if (!getProductId()
          .equals(other.getProductId())) return false;
      if (!getCategoryId()
          .equals(other.getCategoryId())) return false;
      if (!getCategoryCode()
          .equals(other.getCategoryCode())) return false;
      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getUserSession()
          .equals(other.getUserSession())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEventTime().hashCode();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + CATEGORYID_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryId().hashCode();
      hash = (37 * hash) + CATEGORYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryCode().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + USERSESSION_FIELD_NUMBER;
      hash = (53 * hash) + getUserSession().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.ipolyzos.models.Event.JEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.ipolyzos.models.Event.JEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.ipolyzos.models.Event.JEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.ipolyzos.models.Event.JEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.ipolyzos.models.Event.JEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.ipolyzos.models.JEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.ipolyzos.models.JEvent)
        io.ipolyzos.models.Event.JEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.ipolyzos.models.Event.internal_static_io_ipolyzos_models_JEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.ipolyzos.models.Event.internal_static_io_ipolyzos_models_JEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.ipolyzos.models.Event.JEvent.class, io.ipolyzos.models.Event.JEvent.Builder.class);
      }

      // Construct using io.ipolyzos.models.Event.JEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eventTime_ = "";

        eventType_ = "";

        productId_ = "";

        categoryId_ = "";

        categoryCode_ = "";

        brand_ = "";

        price_ = "";

        userId_ = "";

        userSession_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.ipolyzos.models.Event.internal_static_io_ipolyzos_models_JEvent_descriptor;
      }

      @java.lang.Override
      public io.ipolyzos.models.Event.JEvent getDefaultInstanceForType() {
        return io.ipolyzos.models.Event.JEvent.getDefaultInstance();
      }

      @java.lang.Override
      public io.ipolyzos.models.Event.JEvent build() {
        io.ipolyzos.models.Event.JEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.ipolyzos.models.Event.JEvent buildPartial() {
        io.ipolyzos.models.Event.JEvent result = new io.ipolyzos.models.Event.JEvent(this);
        result.eventTime_ = eventTime_;
        result.eventType_ = eventType_;
        result.productId_ = productId_;
        result.categoryId_ = categoryId_;
        result.categoryCode_ = categoryCode_;
        result.brand_ = brand_;
        result.price_ = price_;
        result.userId_ = userId_;
        result.userSession_ = userSession_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.ipolyzos.models.Event.JEvent) {
          return mergeFrom((io.ipolyzos.models.Event.JEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.ipolyzos.models.Event.JEvent other) {
        if (other == io.ipolyzos.models.Event.JEvent.getDefaultInstance()) return this;
        if (!other.getEventTime().isEmpty()) {
          eventTime_ = other.eventTime_;
          onChanged();
        }
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          onChanged();
        }
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          onChanged();
        }
        if (!other.getCategoryId().isEmpty()) {
          categoryId_ = other.categoryId_;
          onChanged();
        }
        if (!other.getCategoryCode().isEmpty()) {
          categoryCode_ = other.categoryCode_;
          onChanged();
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getUserSession().isEmpty()) {
          userSession_ = other.userSession_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.ipolyzos.models.Event.JEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.ipolyzos.models.Event.JEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object eventTime_ = "";
      /**
       * <code>string eventTime = 1;</code>
       * @return The eventTime.
       */
      public java.lang.String getEventTime() {
        java.lang.Object ref = eventTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eventTime = 1;</code>
       * @return The bytes for eventTime.
       */
      public com.google.protobuf.ByteString
          getEventTimeBytes() {
        java.lang.Object ref = eventTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eventTime = 1;</code>
       * @param value The eventTime to set.
       * @return This builder for chaining.
       */
      public Builder setEventTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eventTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventTime() {
        
        eventTime_ = getDefaultInstance().getEventTime();
        onChanged();
        return this;
      }
      /**
       * <code>string eventTime = 1;</code>
       * @param value The bytes for eventTime to set.
       * @return This builder for chaining.
       */
      public Builder setEventTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventType_ = "";
      /**
       * <code>string eventType = 2;</code>
       * @return The eventType.
       */
      public java.lang.String getEventType() {
        java.lang.Object ref = eventType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eventType = 2;</code>
       * @return The bytes for eventType.
       */
      public com.google.protobuf.ByteString
          getEventTypeBytes() {
        java.lang.Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eventType = 2;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eventType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        
        eventType_ = getDefaultInstance().getEventType();
        onChanged();
        return this;
      }
      /**
       * <code>string eventType = 2;</code>
       * @param value The bytes for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>string productId = 3;</code>
       * @return The productId.
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productId = 3;</code>
       * @return The bytes for productId.
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productId = 3;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>string productId = 3;</code>
       * @param value The bytes for productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object categoryId_ = "";
      /**
       * <code>string categoryId = 4;</code>
       * @return The categoryId.
       */
      public java.lang.String getCategoryId() {
        java.lang.Object ref = categoryId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          categoryId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string categoryId = 4;</code>
       * @return The bytes for categoryId.
       */
      public com.google.protobuf.ByteString
          getCategoryIdBytes() {
        java.lang.Object ref = categoryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          categoryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string categoryId = 4;</code>
       * @param value The categoryId to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string categoryId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategoryId() {
        
        categoryId_ = getDefaultInstance().getCategoryId();
        onChanged();
        return this;
      }
      /**
       * <code>string categoryId = 4;</code>
       * @param value The bytes for categoryId to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        categoryId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object categoryCode_ = "";
      /**
       * <code>string categoryCode = 5;</code>
       * @return The categoryCode.
       */
      public java.lang.String getCategoryCode() {
        java.lang.Object ref = categoryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          categoryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string categoryCode = 5;</code>
       * @return The bytes for categoryCode.
       */
      public com.google.protobuf.ByteString
          getCategoryCodeBytes() {
        java.lang.Object ref = categoryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          categoryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string categoryCode = 5;</code>
       * @param value The categoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        categoryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string categoryCode = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategoryCode() {
        
        categoryCode_ = getDefaultInstance().getCategoryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string categoryCode = 5;</code>
       * @param value The bytes for categoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        categoryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 6;</code>
       * @return The brand.
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 6;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 6;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 6;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 7;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 7;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 7;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      /**
       * <code>string price = 7;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        price_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 8;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 8;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 8;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 8;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userSession_ = "";
      /**
       * <code>string userSession = 9;</code>
       * @return The userSession.
       */
      public java.lang.String getUserSession() {
        java.lang.Object ref = userSession_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userSession_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userSession = 9;</code>
       * @return The bytes for userSession.
       */
      public com.google.protobuf.ByteString
          getUserSessionBytes() {
        java.lang.Object ref = userSession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userSession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userSession = 9;</code>
       * @param value The userSession to set.
       * @return This builder for chaining.
       */
      public Builder setUserSession(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userSession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userSession = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserSession() {
        
        userSession_ = getDefaultInstance().getUserSession();
        onChanged();
        return this;
      }
      /**
       * <code>string userSession = 9;</code>
       * @param value The bytes for userSession to set.
       * @return This builder for chaining.
       */
      public Builder setUserSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userSession_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.ipolyzos.models.JEvent)
    }

    // @@protoc_insertion_point(class_scope:io.ipolyzos.models.JEvent)
    private static final io.ipolyzos.models.Event.JEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.ipolyzos.models.Event.JEvent();
    }

    public static io.ipolyzos.models.Event.JEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JEvent>
        PARSER = new com.google.protobuf.AbstractParser<JEvent>() {
      @java.lang.Override
      public JEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.ipolyzos.models.Event.JEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_ipolyzos_models_JEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_ipolyzos_models_JEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/event.proto\022\022io.ipolyzos.models\"" +
      "\256\001\n\006JEvent\022\021\n\teventTime\030\001 \001(\t\022\021\n\teventTy" +
      "pe\030\002 \001(\t\022\021\n\tproductId\030\003 \001(\t\022\022\n\ncategoryI" +
      "d\030\004 \001(\t\022\024\n\014categoryCode\030\005 \001(\t\022\r\n\005brand\030\006" +
      " \001(\t\022\r\n\005price\030\007 \001(\t\022\016\n\006userId\030\010 \001(\t\022\023\n\013u" +
      "serSession\030\t \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_ipolyzos_models_JEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_ipolyzos_models_JEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_ipolyzos_models_JEvent_descriptor,
        new java.lang.String[] { "EventTime", "EventType", "ProductId", "CategoryId", "CategoryCode", "Brand", "Price", "UserId", "UserSession", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
